### ISSUE TITLE
Can you provide please real world example of extensions?

### ISSUE THREAD

**Issue by vinz243** [fastbootmobile/encore-providerlib#1]
That would be awesome. Maybe using youtube API?

BTW, does it support offline?

Thanks,

**Comment by xplodwild** [comment]
One example is the Local Provider at https://github.com/fastbootmobile/encore/tree/master/src/main/java/com/fastbootmobile/encore/providers/localprovider
I'm looking if we can open-source the Spotify provider as a C++ example. YouTube provider is commercial and won't be opensourced for the moment.

**Comment by vinz243** [comment]
Thanks! I'll try it :)

**Comment by vinz243** [comment]
Sorry to bother you, Genymotion, android 5.0, and google play shows not compatible
any idea why :cry: ?

**Comment by vinz243** [comment]
Also, what should callback should I call for fetchArtistAlbums when it has finished?

**Comment by xplodwild** [comment]
I've never used Genymotion so I can't really say. Try to manually install anyway.
When fetchArtistAlbums has finished, you should call onArtistUpdated with an Artist object containing the albums references. You can also call onAlbumUpdated to speed up the display as the app won't need to call getAlbum once it gets the Artist update.

**Comment by vinz243** [comment]
Thanks! How do I read a flac file? Also, why is this empty https://github.com/fastbootmobile/encore/blob/master/src/main/java/com/fastbootmobile/encore/providers/localprovider/PluginService.java#L842 ?

**Comment by xplodwild** [comment]
onAudioData is empty, because this method is called when the plug-in receives audio data from the main app (ie. it is suitable for a DSP effect plug-in, see https://github.com/fastbootmobile/encore/blob/master/src/main/java/com/fastbootmobile/encore/providers/bassboost/PluginService.java#L36). It will never be called for a music provider.

You can read a FLAC file using MediaCodec, see LocalProvider.java MediaCodec part

**Comment by vinz243** [comment]
sorry for the noob question (again!), but how do you stream something remote using MediaCodec? Can I just download the remote file while streaming it?

**Comment by vinz243** [comment]
also, what version of gradle did you used for the app? I get 

```
  Error:(1, 0) Plugin with id 'com.android.application' not found.
```

With 2.4/2.6

**Comment by xplodwild** [comment]
You can use MediaExtractor.setDataSource to set a remote URL for playback. See http://developer.android.com/reference/android/media/MediaExtractor.html#setDataSource(android.content.Context, android.net.Uri, java.util.Map<java.lang.String, java.lang.String>) 
Your code will look something like:

```
  mExtractor.selectTrack(0);
  mCodec = MediaCodec.createDecoderByType(trackMime);
  mCodec.configure(mExtractor.getTrackFormat(track), null, null, 0);
```

Gradle version shouldn't matter. Make sure you have the build.gradle in your project have 
`dependencies {
        classpath 'com.android.tools.build:gradle:1.2.3'
}`

**Comment by vinz243** [comment]
Thanks I'll try ASAP I'll need an API key
